theme = "onedark"

[editor]
line-number = "relative"
# mouse = false
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
git-ignore = false

[keys.normal]
C-s = ":w" # Maps the Ctrl-s to the typable command :w which is an alias for :write (save file)


[keys.insert]
j = { j = "normal_mode" }

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "total-line-numbers", "file-type"]
separator = "â”‚"
mode.normal = "ğŸğŸğŸğŸğŸ"
mode.insert = "ğŸ‘ºğŸ‘ºğŸ‘ºğŸ‘ºğŸ‘º"
mode.select = "ğŸ‘€ğŸ‘€ğŸ‘€ğŸ‘€ğŸ‘€"

[editor.indent-guides]
render = true
character = "â•" # Some characters that work well: "â–", "â”†", "â”Š", "â¸½"
skip-levels = 1

